#! /usr/bin/python
#Author: Tony Allard
#Date: 14 Mar 2016
#Description: A Python script for generating random the MMCR problems as described below

#Usage: MMCR-Tightness-4-3-2.py MaxCargo NumProblems /Path/To/Problems

#Four clusters, three locations per cluster and two vehicles.
#Clusters are laid out in the following fashion
#
#     0
#    / \
#	1   2
#	 \ /	
#	  3
#
#Script generates as many problems as given via an argument for the script. 
#Problems are generated by sampling num cargo between 1 and MaxCargo argument. 
#Cargo origin and desitnation are randomly sampled from all locations, vehicle 
#origin are also randomly sampled from locations within their cluster. 
#Time windows all start from zero, thereby increasing the possibility of 
#concurrency within the problems, as all delivery problems must be solved at once.
#Time windows are sampled uniformly from between minimum estimated delivery 
#(as calculated by a dijkstras algorithm), to 2 * minimum estimated delivery.
#
#Number of vehicles are fixed at 2 vehicles per cluster.
#Capacity is fixed to the number of cargo items, to effectively ensure 
#capacity constraints are not part of the problem. We are only interested in 
#testing the planners performance on time window concurrency.
#Load/Unlaod and travel times are fixed at 2
#Vehicle Utilisation cost is uniform at 2
#Cargo Size is defaulted to 1
#
#NOTE: The location layout remains the same for each problem it is randomly
#generated once. Vehicle initial locations are sampled uniformly from this 
#network. Number of cargo and their delivery is also sampled per problem
#

import sys
import os
import random
import MMCRProbGen

def parseArgs(args):
	argName = ("Max Cargo", "Max Tightness", "Num Problems", "Path")
	if (len(args) != 4):
		print "Error: Incorrect number of arguments."
		raise SyntaxError
	i = 0
	params = dict()
	for x in args[:-1]:
		try:
			params[i] = int(x)
		except ValueError:
			print "Error: %s must be an integer" %argName[i]
			raise SyntaxError
		i+=1
	params[len(args)-1]=str(args[-1])
	return params

def printUsage(name):
	print "Multi-Modal Cargo Routing (MMCR) Problem Generator"
	print "By releasing this code we imply no warranty as to its reliability and its use is entirely at your own risk.\n"
	print "Usage " + name + " maxCargo maxTightness numProblems path\n"
	print "Example: " + name + " 3 2 100 /Path/To/Problems"

def linkSectors(sectors, travelTime, loadTime, unloadTime, connectivityMap):
	pddl = []
	#link sectors 0 and 1
	pddl += MMCRProbGen.linkSectors(sectors[0], sectors[1], travelTime, loadTime, unloadTime, connectivityMap)
	#link sectors 0 and 2
	pddl += MMCRProbGen.linkSectors(sectors[0], sectors[2], travelTime, loadTime, unloadTime, connectivityMap)
	#link sectors 1 and 3
	pddl += MMCRProbGen.linkSectors(sectors[1], sectors[3], travelTime, loadTime, unloadTime, connectivityMap)
	#link sectors 2 and 3
	pddl += MMCRProbGen.linkSectors(sectors[2], sectors[3], travelTime, loadTime, unloadTime, connectivityMap)
	return pddl

def main(args):
	DEFAULT_CARGO_SIZE = 1
	DEFAULT_TRAVEL_TIME = 2
	DEFAULT_LOAD_TIME = 2
	DEFAULT_UNLOAD_TIME = 2
	DEFAULT_COST = 2
	
	output = []
	params = dict()
	try:
		params = parseArgs(args[1:])
	except:
		printUsage(args[0])
		sys.exit(1)

	numProblems = params[2]
	maxCargo = params[0]
	maxTightness = params[1]
	path = params[3]

	numSectors = 4
	numLocations = 3
	numVehicles = 2
	
	#Create 4 Sectors, three locations per sector
	sectors, locations, connectivityMap, initPDDL = MMCRProbGen.createSectors(numSectors, numLocations)

	#Create the number of vehicles per sector as there are cargo
	vehicles, pddl2 = MMCRProbGen.createVehicles(sectors, numVehicles, connectivityMap, DEFAULT_TRAVEL_TIME, DEFAULT_LOAD_TIME, DEFAULT_UNLOAD_TIME, DEFAULT_COST)
	initPDDL += pddl2

	#link sectors
	initPDDL += linkSectors(sectors, DEFAULT_TRAVEL_TIME, DEFAULT_LOAD_TIME, DEFAULT_UNLOAD_TIME, connectivityMap)

	for p in range(0, numProblems):
		pddl = []
		pddl += initPDDL

		#Sample max Cargo
		numCargo = random.randint(1, maxCargo)
		capacityRange = numCargo * DEFAULT_CARGO_SIZE
		tightness = random.uniform(1, maxTightness)
		
		#Add Location Capacity
		pddl += MMCRProbGen.addLocationCapacity(locations, capacityRange)
		#Add Vehicle Capacity
		pddl += MMCRProbGen.addVehicleCapacity(vehicles, capacityRange)
		
		#Create Cargo
		cargoes, pddl2 = MMCRProbGen.createCargo(numCargo, DEFAULT_CARGO_SIZE)
		pddl += pddl2

		#randomly select vehicle origin
		pddl2, vehicleOriginMap = MMCRProbGen.getVehicleOrigin(vehicles, sectors)
		pddl += pddl2

		#randomly select origin and destination for for cargoes
		goals, deliveryInfo, pddl2 = MMCRProbGen.getRandomCargoLocations(cargoes, locations)
		pddl += pddl2

		#Create Random Time Windows
		pddl += MMCRProbGen.determineTimeWindows(deliveryInfo, connectivityMap, vehicleOriginMap, DEFAULT_TRAVEL_TIME, DEFAULT_LOAD_TIME, DEFAULT_UNLOAD_TIME, tightness, False, False)

		#Save problem to file
		name = "Prob-%i-%i-%i-%i-%s-%i"%(len(sectors), len(locations), len(vehicles), len(cargoes), str(tightness).replace('.', '_'), p)
		MMCRProbGen.saveProblem(path+name, locations, vehicles, cargoes, pddl, goals)

#Run Main Function
if __name__ == "__main__":
	main(sys.argv)